[tests]
base = [
  "AddressableLED",
  "AprilTagsVision",
  "ArcadeDrive",
  "ArcadeDriveXboxController",
  "ArmSimulation",
  "CANPDP",
  "DifferentialDriveBot",
  "DigitalCommunication",
  "DriveDistanceOffboard",
  "DutyCycleEncoder",
  "DutyCycleInput",
  "ElevatorProfiledPID",
  "ElevatorSimulation",
  "ElevatorTrapezoidProfile",
  "Encoder",
  "EventLoop",
  "FlywheelBangBangController",
  "GettingStarted",
  "Gyro",
  "GyroMecanum",
  "HatchbotInlined",
  "HatchbotTraditional",
  "HidRumble",
  "HttpCamera",
  "I2CCommunication",
  "IntermediateVision",
  "MecanumBot",
  "MecanumDrive",
  "Mechanism2d",
  "MotorControl",
  "PotentiometerPID",
  "QuickVision",
  "RomiReference",
  "SelectCommand",
  "SimpleDifferentialDriveSimulation",
  "Solenoid",
  "StateSpaceArm",
  "StateSpaceElevator",
  "StateSpaceFlywheel",
  "StateSpaceFlywheelSysId",
  "SwerveBot",
  "SysId",
  "TankDrive",
  "TankDriveXboxController",
  "XrpReference",
]

ignored = [
]
